version: '3'
services:
  opentenbaseHost:
    image: docker.io/library/opentenbase:1.0.0
    networks:
      OpenTenBaseNetWork:
        ipv4_address: 172.16.200.5
    container_name: opentenbaseHost
    restart: unless-stopped
    volumes:
      - "./pgxc_conf/host/:/home/opentenbase/pgxc_conf"
    tty: true

  opentenbaseWait1:
    image: docker.io/library/opentenbasebase:1.0.0
    networks:
      OpenTenBaseNetWork:
        ipv4_address: 172.16.200.10
    container_name: opentenbaseWait1 
    restart: unless-stopped
    volumes:
      - "./pgxc_conf/wait1:/home/opentenbasebase/pgxc_conf"
    tty: true

  opentenbaseWait2:
    image: docker.io/library/opentenbase:1.0.0
    networks:
      OpenTenBaseNetWork:
        ipv4_address: 172.16.200.15
    container_name: opentenbaseWait2 
    restart: unless-stopped
    volumes:
      - "./pgxc_conf/wait2:/home/opentenbase/pgxc_conf"
    tty: true
networks:
  OpenTenBaseNetWork:
    name: OpenTenBaseNetWork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/26
          gateway: 172.16.200.1
      
